db:
  url: jdbc:mysql://root:GIiEnaHLbpEVLmJHTCTAABBcvamRplbH@monorail.proxy.rlwy.net:52423/railway
  username: root
  password: GIiEnaHLbpEVLmJHTCTAABBcvamRplbH
  email: vortexgames19922024@gmail.com
  passwordEmail: mipb ezcg ejco smxk